name: "DeployEnv"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      demoUrl:
        required: true
        type: string
      appUrl:
        required: true
        type: string
    secrets:
      IIS_SERVER_COMPUTER_NAME:
        required: true
      IIS_SERVER_USERNAME:
        required: true
      IIS_SERVER_PASSWORD:
        required: true
      WEBSITE_CONTENT_PATH:
        required: true
      DEMO_CONTENT_PATH:
        required: true

jobs:
  create-app-package:
    uses: ./.github/workflows/createAppPackage.yml
    with:
      environment: ${{ inputs.environment }}
      artifact: files-app
  deploy-app-package:
    needs: create-app-package
    uses: ./.github/workflows/webDeploy.yml
    with:
      environment: ${{ inputs.environment }}
      url: ${{ inputs.appUrl }}
      artifact: files-app
    secrets:
      IIS_SERVER_COMPUTER_NAME: ${{ secrets.IIS_SERVER_COMPUTER_NAME }}
      IIS_SERVER_USERNAME: ${{ secrets.IIS_SERVER_USERNAME }}
      IIS_SERVER_PASSWORD: ${{ secrets.IIS_SERVER_PASSWORD }}
      WEBSITE_CONTENT_PATH: ${{ secrets.WEBSITE_CONTENT_PATH }}
  create-demo-package:
    uses: ./.github/workflows/createDemoPackage.yml
    with:
      artifact: files-demo
  deploy-demo-package:
    needs: create-demo-package
    uses: ./.github/workflows/webDeploy.yml
    with:
      environment: ${{ inputs.environment }}
      url: ${{ inputs.demoUrl }}
      artifact: files-demo
    secrets:
      IIS_SERVER_COMPUTER_NAME: ${{ secrets.IIS_SERVER_COMPUTER_NAME }}
      IIS_SERVER_USERNAME: ${{ secrets.IIS_SERVER_USERNAME }}
      IIS_SERVER_PASSWORD: ${{ secrets.IIS_SERVER_PASSWORD }}
      WEBSITE_CONTENT_PATH: ${{ secrets.DEMO_CONTENT_PATH }}