name: "DeployTest"

on:
  push:
    branches: [ "main" ]

jobs:
  create-package:
    uses: ./.github/workflows/createAppPackage.yml
    with:
      environment: Production
  deploy-package:
    needs: create-package
    uses: ./.github/workflows/webDeploy.yml
    with:
      environment: Production
    secrets:
      IIS_SERVER_COMPUTER_NAME: ${{ secrets.IIS_SERVER_COMPUTER_NAME }}
      IIS_SERVER_USERNAME: ${{ secrets.IIS_SERVER_USERNAME }}
      IIS_SERVER_PASSWORD: ${{ secrets.IIS_SERVER_PASSWORD }}
      WEBSITE_CONTENT_PATH: ${{ secrets.WEBSITE_CONTENT_PATH }}