name: "Run E2E Tests"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    name: E2E tests
    environment: Test
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          working-directory: frontend
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}